"""考试模拟使用的主数据枚举常量。

这里集中放置 `ProduceExamEffectType_*` 等数据库字符串，避免效果器和触发器里到处散落硬编码。
"""


class ExamEffect:
    UNKNOWN = 'ProduceExamEffectType_Unknown'
    AGGRESSIVE_ADDITIVE = 'ProduceExamEffectType_ExamAggressiveAdditive'
    AGGRESSIVE_ADDITIVE_FIX = 'ProduceExamEffectType_ExamAggressiveAdditiveFix'
    AGGRESSIVE_REDUCE = 'ProduceExamEffectType_ExamAggressiveReduce'
    AGGRESSIVE_VALUE_MULTIPLE = 'ProduceExamEffectType_ExamAggressiveValueMultiple'
    ANTI_DEBUFF = 'ProduceExamEffectType_ExamAntiDebuff'
    BLOCK = 'ProduceExamEffectType_ExamBlock'
    BLOCK_ADD_DOWN = 'ProduceExamEffectType_ExamBlockAddDown'
    BLOCK_ADD_MULTIPLE_AGGRESSIVE = 'ProduceExamEffectType_ExamBlockAddMultipleAggressive'
    BLOCK_DEPEND_BLOCK_CONSUMPTION_SUM = 'ProduceExamEffectType_ExamBlockDependBlockConsumptionSum'
    BLOCK_DEPEND_REVIEW = 'ProduceExamEffectType_ExamBlockDependExamReview'
    BLOCK_DOWN = 'ProduceExamEffectType_ExamBlockDown'
    BLOCK_FIX = 'ProduceExamEffectType_ExamBlockFix'
    BLOCK_PER_USE_CARD_COUNT = 'ProduceExamEffectType_ExamBlockPerUseCardCount'
    BLOCK_RESTRICTION = 'ProduceExamEffectType_ExamBlockRestriction'
    BLOCK_VALUE_MULTIPLE = 'ProduceExamEffectType_ExamBlockValueMultiple'
    CARD_CREATE_ID = 'ProduceExamEffectType_ExamCardCreateId'
    CARD_CREATE_SEARCH = 'ProduceExamEffectType_ExamCardCreateSearch'
    CARD_DRAW = 'ProduceExamEffectType_ExamCardDraw'
    CARD_DUPLICATE = 'ProduceExamEffectType_ExamCardDuplicate'
    CARD_MOVE = 'ProduceExamEffectType_ExamCardMove'
    CARD_PLAY_AGGRESSIVE = 'ProduceExamEffectType_ExamCardPlayAggressive'
    CARD_SEARCH_EFFECT_PLAY_COUNT_BUFF = 'ProduceExamEffectType_ExamCardSearchEffectPlayCountBuff'
    CARD_UPGRADE = 'ProduceExamEffectType_ExamCardUpgrade'
    CONCENTRATION = 'ProduceExamEffectType_ExamConcentration'
    CONCENTRATION_LESSON_MULTIPLE_ADDITIVE = 'ProduceExamEffectType_ExamConcentrationLessonMultipleAdditive'
    DEBUFF_RECOVER = 'ProduceExamEffectType_ExamDebuffRecover'
    EFFECT_TIMER = 'ProduceExamEffectType_ExamEffectTimer'
    ENTHUSIASTIC_ADDITIVE = 'ProduceExamEffectType_ExamEnthusiasticAdditive'
    ENTHUSIASTIC_MULTIPLE = 'ProduceExamEffectType_ExamEnthusiasticMultiple'
    EXTRA_TURN = 'ProduceExamEffectType_ExamExtraTurn'
    FORCE_PLAY_CARD_SEARCH = 'ProduceExamEffectType_ExamForcePlayCardSearch'
    FORCE_PLAY_CARD_SEARCH_WITH_COST = 'ProduceExamEffectType_ExamForcePlayCardSearchWithCost'
    FULL_POWER = 'ProduceExamEffectType_ExamFullPower'
    FULL_POWER_LESSON_MULTIPLE_ADDITIVE = 'ProduceExamEffectType_ExamFullPowerLessonMultipleAdditive'
    FULL_POWER_POINT = 'ProduceExamEffectType_ExamFullPowerPoint'
    FULL_POWER_POINT_ADDITIVE = 'ProduceExamEffectType_ExamFullPowerPointAdditive'
    FULL_POWER_POINT_ADDITIVE_FIX = 'ProduceExamEffectType_ExamFullPowerPointAdditiveFix'
    FULL_POWER_POINT_REDUCE = 'ProduceExamEffectType_ExamFullPowerPointReduce'
    GIMMICK_ENTHUSIASTIC = 'ProduceExamEffectType_ExamGimmickEnthusiastic'
    GIMMICK_LESSON_DEBUFF = 'ProduceExamEffectType_ExamGimmickLessonDebuff'
    GIMMICK_PARAMETER_DEBUFF = 'ProduceExamEffectType_ExamGimmickParameterDebuff'
    GIMMICK_PLAY_CARD_LIMIT = 'ProduceExamEffectType_ExamGimmickPlayCardLimit'
    GIMMICK_SLEEPY = 'ProduceExamEffectType_ExamGimmickSleepy'
    GIMMICK_SLUMP = 'ProduceExamEffectType_ExamGimmickSlump'
    GIMMICK_START_TURN_CARD_DRAW_DOWN = 'ProduceExamEffectType_ExamGimmickStartTurnCardDrawDown'
    HAND_GRAVE_COUNT_CARD_DRAW = 'ProduceExamEffectType_ExamHandGraveCountCardDraw'
    ITEM_FIRE_LIMIT_ADD = 'ProduceExamEffectType_ExamItemFireLimitAdd'
    LESSON_PREFIX = 'ProduceExamEffectType_ExamLesson'
    LESSON = 'ProduceExamEffectType_ExamLesson'
    LESSON_ADD_MULTIPLE_LESSON_BUFF = 'ProduceExamEffectType_ExamLessonAddMultipleLessonBuff'
    LESSON_ADD_MULTIPLE_PARAMETER_BUFF = 'ProduceExamEffectType_ExamLessonAddMultipleParameterBuff'
    LESSON_BUFF = 'ProduceExamEffectType_ExamLessonBuff'
    LESSON_BUFF_ADDITIVE = 'ProduceExamEffectType_ExamLessonBuffAdditive'
    LESSON_BUFF_ADDITIVE_FIX = 'ProduceExamEffectType_ExamLessonBuffAdditiveFix'
    LESSON_BUFF_DEPEND_PARAMETER_BUFF = 'ProduceExamEffectType_ExamLessonBuffDependParameterBuff'
    LESSON_BUFF_MULTIPLE = 'ProduceExamEffectType_ExamLessonBuffMultiple'
    LESSON_BUFF_PER_SEARCH_COUNT = 'ProduceExamEffectType_ExamLessonBuffPerSearchCount'
    LESSON_BUFF_REDUCE = 'ProduceExamEffectType_ExamLessonBuffReduce'
    LESSON_DEPEND_AGGRESSIVE = 'ProduceExamEffectType_ExamLessonDependExamCardPlayAggressive'
    LESSON_DEPEND_BLOCK = 'ProduceExamEffectType_ExamLessonDependBlock'
    LESSON_DEPEND_BLOCK_AND_SEARCH_COUNT = 'ProduceExamEffectType_ExamLessonDependBlockAndSearchCount'
    LESSON_DEPEND_BLOCK_CONSUMPTION_SUM = 'ProduceExamEffectType_ExamLessonDependBlockConsumptionSum'
    LESSON_DEPEND_PARAMETER_BUFF = 'ProduceExamEffectType_ExamLessonDependParameterBuff'
    LESSON_DEPEND_PLAY_CARD_COUNT_SUM = 'ProduceExamEffectType_ExamLessonDependPlayCardCountSum'
    LESSON_DEPEND_REVIEW = 'ProduceExamEffectType_ExamLessonDependExamReview'
    LESSON_DEPEND_STAMINA = 'ProduceExamEffectType_ExamLessonDependStamina'
    LESSON_DEPEND_STAMINA_CONSUMPTION_SUM = 'ProduceExamEffectType_ExamLessonDependStaminaConsumptionSum'
    LESSON_FIX = 'ProduceExamEffectType_ExamLessonFix'
    LESSON_FULL_POWER_POINT = 'ProduceExamEffectType_ExamLessonFullPowerPoint'
    LESSON_PER_SEARCH_COUNT = 'ProduceExamEffectType_ExamLessonPerSearchCount'
    LESSON_VALUE_MULTIPLE = 'ProduceExamEffectType_ExamLessonValueMultiple'
    LESSON_VALUE_MULTIPLE_DEPEND_REVIEW_OR_AGGRESSIVE = 'ProduceExamEffectType_ExamLessonValueMultipleDependReviewOrAggressive'
    LESSON_VALUE_MULTIPLE_DOWN = 'ProduceExamEffectType_ExamLessonValueMultipleDown'
    MULTIPLE_ENTHUSIASTIC_LESSON = 'ProduceExamEffectType_ExamMultipleEnthusiasticLesson'
    MULTIPLE_LESSON_BUFF_LESSON = 'ProduceExamEffectType_ExamMultipleLessonBuffLesson'
    OVER_PRESERVATION = 'ProduceExamEffectType_ExamOverPreservation'
    PANIC = 'ProduceExamEffectType_ExamPanic'
    PARAMETER_BUFF = 'ProduceExamEffectType_ExamParameterBuff'
    PARAMETER_BUFF_ADDITIVE = 'ProduceExamEffectType_ExamParameterBuffAdditive'
    PARAMETER_BUFF_ADDITIVE_FIX = 'ProduceExamEffectType_ExamParameterBuffAdditiveFix'
    PARAMETER_BUFF_DEPEND_LESSON_BUFF = 'ProduceExamEffectType_ExamParameterBuffDependLessonBuff'
    PARAMETER_BUFF_MULTIPLE_PER_TURN = 'ProduceExamEffectType_ExamParameterBuffMultiplePerTurn'
    PARAMETER_BUFF_MULTIPLE_PER_TURN_REDUCE = 'ProduceExamEffectType_ExamParameterBuffMultiplePerTurnReduce'
    PARAMETER_BUFF_REDUCE = 'ProduceExamEffectType_ExamParameterBuffReduce'
    PLAYABLE_VALUE_ADD = 'ProduceExamEffectType_ExamPlayableValueAdd'
    PRESERVATION = 'ProduceExamEffectType_ExamPreservation'
    REVIEW = 'ProduceExamEffectType_ExamReview'
    REVIEW_ADDITIVE = 'ProduceExamEffectType_ExamReviewAdditive'
    REVIEW_ADDITIVE_FIX = 'ProduceExamEffectType_ExamReviewAdditiveFix'
    REVIEW_COUNT_ADD = 'ProduceExamEffectType_ExamReviewCountAdd'
    REVIEW_DEPEND_AGGRESSIVE = 'ProduceExamEffectType_ExamReviewDependExamCardPlayAggressive'
    REVIEW_DEPEND_BLOCK = 'ProduceExamEffectType_ExamReviewDependExamBlock'
    REVIEW_MULTIPLE = 'ProduceExamEffectType_ExamReviewMultiple'
    REVIEW_PER_SEARCH_COUNT = 'ProduceExamEffectType_ExamReviewPerSearchCount'
    REVIEW_REDUCE = 'ProduceExamEffectType_ExamReviewReduce'
    REVIEW_VALUE_MULTIPLE = 'ProduceExamEffectType_ExamReviewValueMultiple'
    SEARCH_PLAY_CARD_STAMINA_CONSUMPTION_CHANGE = 'ProduceExamEffectType_ExamSearchPlayCardStaminaConsumptionChange'
    STAMINA_CONSUMPTION_ADD = 'ProduceExamEffectType_ExamStaminaConsumptionAdd'
    STAMINA_CONSUMPTION_ADD_FIX = 'ProduceExamEffectType_ExamStaminaConsumptionAddFix'
    STAMINA_CONSUMPTION_DOWN = 'ProduceExamEffectType_ExamStaminaConsumptionDown'
    STAMINA_CONSUMPTION_DOWN_FIX = 'ProduceExamEffectType_ExamStaminaConsumptionDownFix'
    STAMINA_DAMAGE = 'ProduceExamEffectType_ExamStaminaDamage'
    STAMINA_RECOVER = 'ProduceExamEffectType_ExamStaminaRecover'
    STAMINA_RECOVER_FIX = 'ProduceExamEffectType_ExamStaminaRecoverFix'
    STAMINA_RECOVER_MULTIPLE = 'ProduceExamEffectType_ExamStaminaRecoverMultiple'
    STAMINA_RECOVER_RESTRICTION = 'ProduceExamEffectType_ExamStaminaRecoverRestriction'
    STAMINA_REDUCE = 'ProduceExamEffectType_ExamStaminaReduce'
    STAMINA_REDUCE_FIX = 'ProduceExamEffectType_ExamStaminaReduceFix'
    STATUS_ENCHANT = 'ProduceExamEffectType_ExamStatusEnchant'
    STATUS_ENCHANT_ENCORE = 'ProduceExamEffectType_ExamStatusEnchantEncore'
    STANCE_LOCK = 'ProduceExamEffectType_StanceLock'
    STANCE_RESET = 'ProduceExamEffectType_ExamStanceReset'
    ADD_GROW_EFFECT = 'ProduceExamEffectType_ExamAddGrowEffect'


class GrowEffect:
    AGGRESSIVE_ADD = 'ProduceCardGrowEffectType_AggressiveAdd'
    BLOCK_ADD = 'ProduceCardGrowEffectType_BlockAdd'
    BLOCK_REDUCE = 'ProduceCardGrowEffectType_BlockReduce'
    CARD_STATUS_ENCHANT_CHANGE = 'ProduceCardGrowEffectType_CardStatusEnchantChange'
    COST_ADD = 'ProduceCardGrowEffectType_CostAdd'
    COST_REDUCE = 'ProduceCardGrowEffectType_CostReduce'
    COST_AGGRESSIVE_ADD = 'ProduceCardGrowEffectType_CostAggressiveAdd'
    COST_AGGRESSIVE_REDUCE = 'ProduceCardGrowEffectType_CostAggressiveReduce'
    COST_REVIEW_ADD = 'ProduceCardGrowEffectType_CostReviewAdd'
    COST_REVIEW_REDUCE = 'ProduceCardGrowEffectType_CostReviewReduce'
    COST_PARAMETER_BUFF_ADD = 'ProduceCardGrowEffectType_CostParameterBuffAdd'
    COST_PARAMETER_BUFF_REDUCE = 'ProduceCardGrowEffectType_CostParameterBuffReduce'
    COST_PARAMETER_BUFF_MULTIPLE_PER_TURN_REDUCE = 'ProduceCardGrowEffectType_CostParameterBuffMultiplePerTurnReduce'
    COST_LESSON_BUFF_ADD = 'ProduceCardGrowEffectType_CostLessonBuffAdd'
    COST_LESSON_BUFF_REDUCE = 'ProduceCardGrowEffectType_CostLessonBuffReduce'
    COST_FULL_POWER_POINT_ADD = 'ProduceCardGrowEffectType_CostFullPowerPointAdd'
    COST_FULL_POWER_POINT_REDUCE = 'ProduceCardGrowEffectType_CostFullPowerPointReduce'
    COST_PENETRATE_ADD = 'ProduceCardGrowEffectType_CostPenetrateAdd'
    COST_PENETRATE_REDUCE = 'ProduceCardGrowEffectType_CostPenetrateReduce'
    EFFECT_ADD = 'ProduceCardGrowEffectType_EffectAdd'
    EFFECT_CHANGE = 'ProduceCardGrowEffectType_EffectChange'
    FULL_POWER_POINT_ADD = 'ProduceCardGrowEffectType_FullPowerPointAdd'
    FULL_POWER_POINT_REDUCE = 'ProduceCardGrowEffectType_FullPowerPointReduce'
    INITIAL_ADD = 'ProduceCardGrowEffectType_InitialAdd'
    LESSON_ADD = 'ProduceCardGrowEffectType_LessonAdd'
    LESSON_BUFF_ADD = 'ProduceCardGrowEffectType_LessonBuffAdd'
    LESSON_COUNT_ADD = 'ProduceCardGrowEffectType_LessonCountAdd'
    LESSON_COUNT_REDUCE = 'ProduceCardGrowEffectType_LessonCountReduce'
    LESSON_DEPEND_AGGRESSIVE_ADD = 'ProduceCardGrowEffectType_LessonDependExamCardPlayAggressiveAdd'
    LESSON_DEPEND_BLOCK_ADD = 'ProduceCardGrowEffectType_LessonDependBlockAdd'
    LESSON_DEPEND_REVIEW_ADD = 'ProduceCardGrowEffectType_LessonDependExamReviewAdd'
    LESSON_REDUCE = 'ProduceCardGrowEffectType_LessonReduce'
    PARAMETER_BUFF_MULTIPLE_PER_TURN_ADD = 'ProduceCardGrowEffectType_ParameterBuffMultiplePerTurnAdd'
    PARAMETER_BUFF_TURN_ADD = 'ProduceCardGrowEffectType_ParameterBuffTurnAdd'
    PLAY_EFFECT_TRIGGER_CHANGE = 'ProduceCardGrowEffectType_PlayEffectTriggerChange'
    PLAY_MOVE_POSITION_TYPE_CHANGE = 'ProduceCardGrowEffectType_PlayMovePositionTypeChange'
    PLAY_TRIGGER_CHANGE = 'ProduceCardGrowEffectType_PlayTriggerChange'
    REVIEW_ADD = 'ProduceCardGrowEffectType_ReviewAdd'
    STAMINA_CONSUMPTION_DOWN_TURN_ADD = 'ProduceCardGrowEffectType_StaminaConsumptionDownTurnAdd'


class ExamPhase:
    NONE = 'ProduceExamPhaseType_None'
    START_EXAM = 'ProduceExamPhaseType_ExamStartExam'
    START_TURN = 'ProduceExamPhaseType_ExamStartTurn'
    TURN_TIMER = 'ProduceExamPhaseType_ExamTurnTimer'
    TURN_INTERVAL = 'ProduceExamPhaseType_ExamTurnInterval'
    STATUS_CHANGE = 'ProduceExamPhaseType_ExamStatusChange'
    STAMINA_REDUCE = 'ProduceExamPhaseType_ExamStaminaReduce'
    STAMINA_REDUCE_CARD = 'ProduceExamPhaseType_ExamStaminaReduceCard'
    BUFF_CONSUME = 'ProduceExamPhaseType_ExamBuffConsume'
    START_EXAM_PLAY = 'ProduceExamPhaseType_StartExamPlay'
    START_PLAY = 'ProduceExamPhaseType_StartPlay'
    CARD_PLAY = 'ProduceExamPhaseType_ExamCardPlay'
    CARD_PLAY_AFTER = 'ProduceExamPhaseType_ExamCardPlayAfter'
    SEARCH_CARD_PLAY = 'ProduceExamPhaseType_ExamSearchCardPlay'
    PLAY_TURN_COUNT_INTERVAL = 'ProduceExamPhaseType_ExamPlayTurnCountInterval'
    PLAY_COUNT_INTERVAL = 'ProduceExamPhaseType_ExamPlayCountInterval'
    PLAY_COUNT_INTERVAL_AFTER = 'ProduceExamPhaseType_ExamPlayCountIntervalAfter'
    TURN_SKIP = 'ProduceExamPhaseType_ExamTurnSkip'
    END_TURN = 'ProduceExamPhaseType_ExamEndTurn'
    END_TURN_INTERVAL = 'ProduceExamPhaseType_ExamEndTurnInterval'
    CARD_MOVE_HAND = 'ProduceExamPhaseType_ExamCardMoveHand'
    CARD_MOVE_LOST = 'ProduceExamPhaseType_ExamCardMoveLost'
    CARD_MOVE_GRAVE = 'ProduceExamPhaseType_ExamCardMoveGrave'
    STANCE_CHANGE_CONCENTRATION = 'ProduceExamPhaseType_ExamStanceChangeConcentration'
    STANCE_CHANGE_FULL_POWER = 'ProduceExamPhaseType_ExamStanceChangeFullPower'
    STANCE_CHANGE_PRESERVATION = 'ProduceExamPhaseType_ExamStanceChangePreservation'
    STANCE_CHANGE_COUNT_INTERVAL = 'ProduceExamPhaseType_ExamStanceChangeCountInterval'
    STANCE_CHANGE_FROM_CONCENTRATION = 'ProduceExamPhaseType_ExamStanceChangeFromConcentration'
    STANCE_CHANGE_FROM_FULL_POWER = 'ProduceExamPhaseType_ExamStanceChangeFromFullPower'
    AGGRESSIVE_UP_INTERVAL = 'ProduceExamPhaseType_ExamAggressiveUpInterval'


class FieldStatus:
    UNKNOWN = 'ProduceExamFieldStatusType_Unknown'
    BLOCK_UP = 'ProduceExamFieldStatusType_BlockUp'
    CARD_PLAY_AGGRESSIVE_UP = 'ProduceExamFieldStatusType_CardPlayAggressiveUp'
    CARD_SEARCH_COUNT_UP = 'ProduceExamFieldStatusType_CardSearchCountUp'
    CONDITION_THRESHOLD_MULTIPLE = 'ProduceExamFieldStatusType_ConditionThresholdMultiple'
    CONDITION_THRESHOLD_MULTIPLE_DOWN = 'ProduceExamFieldStatusType_ConditionThresholdMultipleDown'
    CONCENTRATION_CHANGE_COUNT_UP = 'ProduceExamFieldStatusType_ConcentrationChangeCountUp'
    CONCENTRATION_UP = 'ProduceExamFieldStatusType_ConcentrationUp'
    FULL_POWER_CHANGE_COUNT_UP = 'ProduceExamFieldStatusType_FullPowerChangeCountUp'
    FULL_POWER_POINT_GET_SUM_UP = 'ProduceExamFieldStatusType_FullPowerPointGetSumUp'
    FULL_POWER_POINT_UP = 'ProduceExamFieldStatusType_FullPowerPointUp'
    FULL_POWER_UP = 'ProduceExamFieldStatusType_FullPowerUp'
    LESSON_BUFF_UP = 'ProduceExamFieldStatusType_LessonBuffUp'
    NO_BLOCK = 'ProduceExamFieldStatusType_NoBlock'
    NO_STANCE = 'ProduceExamFieldStatusType_NoStance'
    PARAMETER_BUFF = 'ProduceExamFieldStatusType_ParameterBuff'
    PARAMETER_BUFF_MULTIPLE_PER_TURN_UP = 'ProduceExamFieldStatusType_ParameterBuffMultiplePerTurnUp'
    PARAMETER_BUFF_UP = 'ProduceExamFieldStatusType_ParameterBuffUp'
    PLAY_CARD_LESSON = 'ProduceExamFieldStatusType_PlayCardLesson'
    PLAY_CARD_SKILL = 'ProduceExamFieldStatusType_PlayCardSkill'
    PRESERVATION_CHANGE_COUNT_UP = 'ProduceExamFieldStatusType_PreservationChangeCountUp'
    PRESERVATION_UP = 'ProduceExamFieldStatusType_PreservationUp'
    REMAINING_TURN = 'ProduceExamFieldStatusType_RemainingTurn'
    REVIEW_UP = 'ProduceExamFieldStatusType_ReviewUp'
    STAMINA_CONSUMPTION_DOWN = 'ProduceExamFieldStatusType_StaminaConsumptionDown'
    STAMINA_LESS_MULTIPLE = 'ProduceExamFieldStatusType_StaminaLessMultiple'
    STAMINA_UP_MULTIPLE = 'ProduceExamFieldStatusType_StaminaUpMultiple'
    STANCE_CHANGE_COUNT_UP = 'ProduceExamFieldStatusType_StanceChangeCountUp'
    TURN_PROGRESS_UP = 'ProduceExamFieldStatusType_TurnProgressUp'


class TriggerCheck:
    UNKNOWN = 'ProduceExamTriggerCheckType_Unknown'
    NOT = 'ProduceExamTriggerCheckType_Not'


class LessonType:
    UNKNOWN = 'ProduceStepLessonType_Unknown'


class SearchValue:
    PRODUCE_CARD_SEARCH_ID = 'produceCardSearchId'
    EFFECT_VALUE_1 = 'effectValue1'
    EFFECT_VALUE_2 = 'effectValue2'
