'use strict';
const $=id=>document.getElementById(id);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>v==null?'—':Number(v).toLocaleString('zh-CN',{maximumFractionDigits:0});
const dec=(v,n=3)=>v==null?'—':Number(v).toFixed(n);
const time=v=>v?new Date(v).toLocaleTimeString('zh-CN',{hour12:false}):'—';
const deadlineTime=v=>v?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}):'—';
const names={'saki-wild':'野花咲季 · 好印象','saki-hif':'HIF 咲季 · 强气','hiro-hif':'HIF 广 · 集中好调','ume-campus':'Campus mode!! 佑芽 · 全力','liliya-xmas':'圣诞莉莉娅 · 干劲盾'};
const colors={'saki-wild':'#16857b','saki-hif':'#d88719','hiro-hif':'#3867b8','ume-campus':'#9c59b4','liliya-xmas':'#c34579'};
const memoryNames={none:'无 HIF 回忆',hif:'HIF 回忆可用',legacy:'旧任务：仅 HIF 回忆可用'};
let state=null,rows=[],detail=null,cursor=0,playTimer=null,selected=null,loadSequence=0,stateBusy=false,episodeBusy=false;
let logBusy=false,logPaused=false,logFollow=true,logVersion=null,logSequence=0;
async function api(path){const r=await fetch(path,{cache:'no-store',signal:AbortSignal.timeout(45000)});const d=await r.json();if(!r.ok)throw Error(d.error||'读取失败');return d;}
function error(s){$('error').textContent=s;$('error').hidden=!s;}
function metric(label,value,note){return `<div class="metric"><span class="label">${label}</span><strong class="value">${value}</strong><p>${note}</p></div>`;}
function bars(id,counts,keys,suffix){const max=Math.max(1,...Object.values(counts||{}));$(id).innerHTML=keys.map(k=>`<div class="dist-item"><span>${num(counts?.[k]||0)} 局</span><div class="dist-bar" style="height:${Math.max(3,75*(counts?.[k]||0)/max)}px"></div><span>${k}${suffix}</span></div>`).join('');}
function drawChart(){if(!state)return;const mode=$('chart-mode').value;const points=((mode==='best4'?state.series?.best4_validation:mode==='play'?state.series?.play_validation:state.series?.validation)||[]).filter(p=>Number.isFinite(p.decisions));
 const lines=mode==='best4'?[{label:'四局最高分 · 各偶像自身起点 1.000',color:'#d88719',points:points.map(p=>({x:p.decisions,y:p.validation_index}))}]:mode==='play'?[{label:'固定卡组操作 · 自身起点 1.000',color:'#9c59b4',points:points.map(p=>({x:p.decisions,y:p.validation_index}))}]:mode==='index'?[{label:'当前权重',color:'#3867b8',points:points.map(p=>({x:p.decisions,y:p.validation_index}))},{label:'历史最佳',color:'#16857b',points:points.map(p=>({x:p.decisions,y:p.best_index}))}]:mode==='memory'?['none','hif'].map((id,i)=>({label:memoryNames[id],color:['#3867b8','#16857b'][i],points:points.map(p=>({x:p.decisions,y:p.memory_modes?.[id]?.normalized_mean}))})):Object.entries(names).map(([id,label])=>({label,color:colors[id],points:points.map(p=>({x:p.decisions,y:p.profiles?.[id]?.normalized_mean}))}));
 lines.forEach(l=>l.points=l.points.filter(p=>Number.isFinite(p.y)));const all=lines.flatMap(l=>l.points);if(!all.length){$('score-chart').textContent=mode==='memory'&&!state.memory_conditions?.enabled?'旧任务没有独立的有 / 无 HIF 回忆评估分组。':'等待完整评估记录…';$('chart-legend').textContent='';$('chart-note').textContent='';return;}
 const W=Math.max(330,$('score-chart').clientWidth),H=265,L=47,R=20,T=15,B=37,maxX=Math.max(1,...all.map(p=>p.x));let low=['index','play','best4'].includes(mode)?Math.min(.95,...all.map(p=>p.y))-.025:0,high=Math.max(['index','play','best4'].includes(mode)?1.02:.1,...all.map(p=>p.y));high+=Math.max(.015,(high-low)*.07);
 const x=v=>L+v/maxX*(W-L-R),y=v=>H-B-(v-low)/(high-low)*(H-T-B);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="固定评估曲线"><title>固定考试条件的评估结果，横轴有效决策数</title>`;
 for(let i=0;i<=4;i++){const v=low+(high-low)*i/4;svg+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="#e6eaf1"/><text x="${L-8}" y="${y(v)+4}" text-anchor="end">${v.toFixed(2)}</text>`;}
 for(let i=0;i<=4;i++)svg+=`<text x="${x(maxX*i/4)}" y="${H-10}" text-anchor="${i===0?'start':i===4?'end':'middle'}">${num(maxX*i/4)}</text>`;
 for(const l of lines){svg+=`<polyline points="${l.points.map(p=>x(p.x)+','+y(p.y)).join(' ')}" fill="none" stroke="${l.color}" stroke-width="2.4"/>`;for(const p of l.points)svg+=`<circle cx="${x(p.x)}" cy="${y(p.y)}" r="3" fill="${l.color}"><title>${esc(l.label)} · ${num(p.x)} 次 · ${dec(p.y)}</title></circle>`;}
 $('score-chart').innerHTML=svg+'</svg>';$('chart-legend').innerHTML=lines.map(l=>`<span><i style="background:${l.color}"></i>${esc(l.label)}</span>`).join('');$('chart-note').textContent=mode==='best4'?'每套新构筑使用固定的四个独立随机种子，取四局最高分，再按各偶像自身基线比较。旧均分曲线保留；这条曲线使用新目标的切换点作为 1.000。验证不使用搜索，不参与梯度更新。':mode==='play'?'固定公开卡组和资源，仅比较打牌操作；开发评估，不参与训练。沿用当前评估套件的固定基线，调整梯度批量不会重建基线。':mode==='index'?(state.search?.enabled?'本次架构迁移后的权重作为起点 = 1.000；此前结果另存。':state.practice?.construction_reference?'同名限额调整后的权重作为新起点 = 1.000；旧构筑结果另存。':'起点 = 1.000。')+'按偶像、课程、饮料容量和回忆环境分组等权比较；指数变化不是原始均分增长率。当前权重可能低于已保存的最佳权重。':mode==='memory'?'归一化分按环境条件分组；观察无 HIF 回忆时是否也在进步。组间分数差不等于回忆的因果价值。':'归一化分去掉人为全局倍率与参考尺度；每位偶像主要看自身曲线，不用于直接排名强度。';
}
function comparisonRow(label,baseline={},current={}){const a=baseline.normalized_mean,b=current.normalized_mean,gain=a>0&&b!=null?b/a-1:null;return `<tr><td>${esc(label)}</td><td>${num(current.count)}</td><td>${dec(a)}</td><td>${dec(b)}</td><td class="${gain==null?'':gain>=0?'up':'down'}">${gain==null?'—':(gain>=0?'+':'')+(gain*100).toFixed(1)+'%'}</td></tr>`;}
function renderMemoryConditions(){const m=state.memory_conditions||{},counts=state.distributions?.memory_mode_counts||{};$('memory-status').textContent=m.status||'旧任务：仅 HIF 回忆可用';$('memory-train-counts').textContent=m.enabled?`最近一批：无 HIF ${num(counts.none||0)} 局 · HIF 可用 ${num(counts.hif||0)} 局`:'';
 $('memory-table').innerHTML=m.enabled?['none','hif'].map(k=>comparisonRow(memoryNames[k],m.baseline?.[k],m.validation?.[k])).join(''):'<tr><td colspan="5">旧任务没有无 HIF 回忆场景，不推算这一组的成绩。</td></tr>';
 const base=m.condition_baseline||{},latest=m.condition_validation||{},keys=[...new Set([...Object.keys(base),...Object.keys(latest)])].sort();$('condition-table').innerHTML=keys.length?keys.map(k=>{const c=latest[k]||base[k],mode=c.memory_mode||k.split('|')[0],capacity=c.drink_capacity??k.split('drinks=')[1];return comparisonRow(`${memoryNames[mode]||mode} · ${capacity} 瓶容量`,base[k],latest[k]);}).join(''):'<tr><td colspan="5">等待完整交叉条件评估。</td></tr>';
}
function renderState(){const p=state.progress||{},m=state.metrics||{};const plannedHours=state.run?.started_at&&state.run?.expected_training_end?(new Date(state.run.expected_training_end)-new Date(state.run.started_at))/3600000:(p.max_minutes||480)/60;const status=p.event==='evaluating'&&p.batches===0?'正在建立新场景的起点基线':({running:'训练进行中',complete:'本轮训练完成',failed:'训练出现错误',training_complete:'正在最终评估'}[state.status]||state.status||'准备中');
 if(window.renderSearch)window.renderSearch(state);
 $('pool-rule').textContent=state.setup?.pool_rules?.description||'旧任务：尚未记录支援卡槽位规则';$('deck-count-note').textContent=state.setup?.pool_rules?.count_note||'一番星不占这 18–25 个槽位，实际入场张数可能更多。';
 $('run-status').textContent=status+(state.trainer_alive===false?' · 进程已退出':'');$('run-id').textContent=state.run?.id||'';$('run-time').textContent=`最近训练记录 ${time(state.updated_at)} · 心跳 ${time(state.monitor?.checked_at)} · 预计训练结束 ${deadlineTime(state.run?.expected_training_end)}（上海时间，之后做最终评估）`;
 const validationNote=m.validation_batch==null?'等待固定验证':`第 ${num(m.validation_batch)} 批验证 · ${m.validation_from_current_revision?'本版本':'接续前的权重'}`;
 $('metrics').innerHTML=metric('完成批次 / 有效决策',`${num(p.batches)} <small>批</small>`,`${num(p.decisions)} 次有效决策`)+metric('历史最佳评估指数',dec(m.best_validation_index),m.best_validation_index>0?'起点 1.000 · 最佳权重已单独保存':'正在建立起点基线')+metric('最近评估指数',dec(m.validation_index),validationNote)+metric('训练累计时间',`${dec((p.elapsed_minutes||0)/60,1)} <small>小时</small>`,`本轮时段 ${dec(plannedHours,1)} 小时 · 每批目标 ${num(p.batch_decisions||2048)} 次`);
 $('profile-table').innerHTML=(state.profiles||[]).map(p=>{const a=p.baseline?.normalized_mean,b=p.validation?.normalized_mean,gain=a>0&&b!=null?b/a-1:null;return `<tr><td><span style="color:${colors[p.id]||'#3867b8'}">●</span> ${esc(names[p.id]||p.id)}</td><td>${num(p.baseline?.mean)}</td><td>${num(p.validation?.mean)}</td><td class="${gain>=0?'up':'down'}">${gain==null?'—':(gain>=0?'+':'')+(gain*100).toFixed(1)+'%'}</td><td>${num(p.training?.mean)}</td></tr>`;}).join('');
 $('eval-count').textContent=`固定评估 · 总计 ${num(state.setup?.eval_episodes)} 局`;bars('capacity-bars',state.distributions?.drink_capacity_counts,[0,1,2,3,4],' 瓶');bars('deck-bars',state.distributions?.deck_size_counts,[18,19,20,21,22,23,24,25],' 张');renderMemoryConditions();drawChart();
 const pr=state.practice||{};$('practice-section').hidden=!pr.enabled;
 if(pr.enabled){const mm=pr.modes||{};$('practice-summary').textContent=`最近一批：普通 ${num(mm.normal)} 局 / 构筑探索 ${num(mm.draft)} 局 / 考试探索 ${num(mm.exam)} 局 · ${num(pr.fork_prefixes)} 套构筑追加 ${num(pr.fork_exams)} 场牌序复测 · 场景库 ${num(pr.bank?.size)} 条`;
 const opt=state.optimizer||{}, rates=opt.actual?.rates||{}, plan=opt.schedule;const lrNote=$('learning-rate-summary');if(lrNote)lrNote.textContent=Object.keys(rates).length?`实际学习率：${Object.entries(rates).map(([k,v])=>`${({exam:'共享／打牌',draft:'构筑',guidance:'指导',drink:'饮料',memory:'回忆'})[k]} ${Number(v).toFixed(6)}`).join(' · ')}${plan?`。先保持 ${Number(plan.hold_minutes/60).toFixed(2)} 小时，再用 ${plan.decay_minutes/60} 小时线性衰减至起始值的 ${Math.round(plan.min_ratio*100)}%；当前${({hold:'保持',decay:'衰减',floor:'最低值'})[opt.actual.stage]||opt.actual.stage}阶段。`:''}`:'';
 const d=pr.duplicates||{},dc=pr.config?.duplicates||{},exceptions=dc.max_same_name_overrides||{};const e2=$('explore2-summary');const caps=dc.max_same_name?`同名最多 ${num(dc.max_same_name)} 张（强化／绿豆合并）${Object.entries(exceptions).map(([name,limit])=>`；${name}最多 ${num(limit)} 张`).join('')}`:'';const softActive=!dc.max_same_name||Math.max(dc.max_same_name,...Object.values(exceptions))>dc.free_copies;const penaltyText=softActive?`重复卡从第 ${num(dc.free_copies+1)} 张起软惩罚，系数 ${dec(dc.coefficient)}`:'硬上限内不额外扣重复罚分';if(e2)e2.textContent=dc.enabled?`更新前采样目标 ${num(pr.batch_decisions_target)} 次有效决策 · ${caps} · ${penaltyText} · 最近 ${num(d.penalized_decks)} / ${num(d.joint_decks)} 套构筑受罚。曲线保留真实考试分数。${pr.construction_reference?.start_batch!=null?` 本次限制从第 ${num(pr.construction_reference.start_batch)} 批以当时权重建立新起点；固定卡组操作曲线使用各自评估种子套件的基线。`:''}`:'';
 const rep=pr.fork_coverage, upd=pr.update_coverage;const repEl=$('repeat-summary'),updEl=$('update-coverage-summary');if(repEl)repEl.textContent=rep?`多局评价：${num(rep.repeated_prefixes)} / ${num(rep.joint_prefixes)} 套构筑（${dec(rep.coverage*100,0)}%） · ${pr.committed_objective==='best_of_k'?'构筑取四局最高分，打牌按对最高分的贡献学习':'构筑用均分，打牌保留各局回报'} · ${Object.entries(rep.groups||{}).map(([key,g])=>`${key} ${g.repeated_prefixes}/${g.joint_prefixes}`).join('；')}`:'等待本版本的多局评价统计';if(updEl)updEl.textContent=upd?`实际更新覆盖：${num(upd.accepted_unique)} / ${num(upd.record_count)} 条（${dec(upd.accepted_fraction*100,1)}%） · ${num(pr.optimizer_steps)} 次参数更新${pr.stopping_block?` · 停止块 KL ${dec(pr.stopping_block.kl,4)} / 阈值 ${dec(pr.stopping_block.threshold,4)}`:''}${pr.post_update_kl?.mean_kl!=null?` · 更新后分层抽查 KL ${dec(pr.post_update_kl.mean_kl,4)}`:''}。覆盖统计只计算实际用于已接受更新的唯一记录。`:'等待本版本的更新覆盖统计';
 if(updEl&&pr.critic_update_coverage){const v=pr.critic_update_coverage,c=pr.critic_completion||{};updEl.textContent+=` 价值更新覆盖：${num(v.accepted_unique)} / ${num(v.record_count)} 条（${dec(v.accepted_fraction*100,1)}%），其中冻结策略补训 ${num(c.completed_records)} 条 / ${num(c.optimizer_steps)} 步。KL目标 ${dec(pr.target_kl,3)}。`;}
 if(updEl&&pr.signed_credit){const c=pr.signed_credit.groups?.all_exam||{},s=pr.search_learning||{};updEl.textContent+=` 打牌学习信号：正 ${num(c.ppo_positive||0)} / 负 ${num(c.ppo_negative||0)} / 零 ${num(c.ppo_zero||0)}；已用于更新的负信号 ${num(c.accepted_ppo_negative||0)}。搜索有学习方向 ${num(s.weighted_roots)} / ${num(s.roots)} 根；行为熵 ${dec(100*s.mean_behavior_entropy,1)}% / 学习目标熵 ${dec(100*s.mean_target_entropy,1)}%。`;}
 const paired=pr.latest_play?.paired_vs_baseline,ci=paired?.normalized_gain_ci95;$('play-summary').textContent=pr.latest_play?`固定卡组操作指数 ${dec(pr.latest_play.validation_index)} · 第 ${num(pr.latest_play.batch)} 批${pr.latest_play.replicas?` · 每组 ${num(pr.latest_play.replicas)} 个种子，共 ${num(paired?.episodes)} 局`:''}${ci?` · 相对基线归一化分差 ${dec(paired.normalized_gain,4)}，95% 描述区间 [${dec(ci[0],4)}, ${dec(ci[1],4)}]`:''} · 请在曲线菜单选择“固定卡组操作指数”。`:'正在建立固定卡组操作基线…';}
 const alert=state.errors?.alert||state.monitor?.alert;error(alert?String(alert):'');$('updated').textContent=`已连接 · 页面同步 ${time(state.checked_at||new Date())}`;$('live-dot').style.background=state.trainer_alive===false?'#b7424c':'#16857b';
}
async function refreshState(){if(stateBusy)return;stateBusy=true;try{const next=await api('/api/generalist');if(!next.available)throw Error('尚未找到通用训练任务');const oldRun=state?.run?.id;state=next;renderState();if(oldRun&&oldRun!==state.run.id){stop();detail=null;selected=null;$('replay-board').hidden=true;$('replay-empty').hidden=false;refreshEpisodes();}}catch(e){error('面板连接失败，将自动重试：'+e.message);$('updated').textContent='连接中断';$('live-dot').style.background='#b7424c';}finally{stateBusy=false;}}
async function refreshLogs(){if(logBusy||logPaused)return;logBusy=true;const seq=logSequence;try{const d=await api('/api/generalist/logs?source='+$('log-source').value);if(seq!==logSequence)return;$('log-status').textContent=`检查 ${time(new Date())} · 文件更新 ${time(d.modified_at)} · ${d.line_count||0} 行`;if(logFollow&&d.version!==logVersion){$('log-output').textContent=d.text||(d.available?'暂无日志内容。':'等待日志生成。');$('log-output').scrollTop=$('log-output').scrollHeight;logVersion=d.version;}}catch(e){$('log-status').textContent='日志读取失败：'+e.message;}finally{logBusy=false;}}
function profileId(row){return typeof row.profile==='object'?row.profile.id:row.profile||row.profile_id;}
function key(row){return `${row.mode}/${row.file}/${row.seed}`;}
function supportText(row){return row.support_card_limit!=null?` · 支援卡 ${num(row.support_card_count)} / ${num(row.support_card_limit)} 张`:'';}
function renderEpisodes(){const filter=$('profile-select').value,memory=$('memory-select').value,drink=$('drink-select').value;const list=rows.filter(r=>(filter==='all'||profileId(r)===filter)&&(memory==='all'||(r.memory_mode||'legacy')===memory)&&(drink==='all'||String(r.drink_capacity)===drink));$('episode-list').innerHTML=list.length?list.map(r=>`<button data-episode="${esc(key(r))}" class="${key(r)===selected?'active':''}"><span>${esc(names[profileId(r)]||profileId(r))}</span><div class="episode-score">${num(r.score)} 分</div><span class="caption">${r.deck_size} 张${supportText(r)} · 容量 ${r.drink_capacity} · 实带 ${r.drinks?.length||0} 瓶<br>${esc(r.memory_status||memoryNames[r.memory_mode||'legacy'])} · 回忆容量 ${num(r.memory_capacity)} · 已选 ${num(r.selected_memory_count)}<br>${esc(r.course_id||'')}<br>seed ${r.seed}</span></button>`).join(''):'这个筛选下暂无最近对局。';}
async function refreshEpisodes(){if(episodeBusy)return;episodeBusy=true;const mode=$('mode-select').value;try{const d=await api('/api/generalist/episodes?mode='+mode);if(mode!==$('mode-select').value)return;const next=Array.isArray(d)?d:d.episodes||[];const changed=JSON.stringify(next.map(r=>[key(r),r.score]))!==JSON.stringify(rows.map(r=>[key(r),r.score]));rows=next;if(changed||!$('episode-list').querySelector('button'))renderEpisodes();}catch(e){$('episode-list').textContent=e.message;}finally{episodeBusy=false;if(mode!==$('mode-select').value)refreshEpisodes();}}
function cards(items){return (items||[]).map(c=>`<div class="card-tile">${c.source_type==='support'?'<span class="support-badge">支援专属</span>':''}${c.icon?`<img src="${esc(c.icon)}" alt="${esc(c.name)}" loading="lazy">`:''}<div>${esc(c.name||c.definition_id||c.id)}</div><small>${esc((c.guidance_names||[]).join(' / ')||Object.entries(c.customizations||{}).map(([k,v])=>`指导 ${k}×${v}`).join(' / '))}</small></div>`).join('');}
function drinks(items){return items?.length?items.map(d=>`<div class="drink-tile">${d.icon?`<img src="${esc(d.icon)}" alt="${esc(d.name)}" loading="lazy">`:''}<span>${esc(d.name||d.id||d)}</span></div>`).join(''):'<span class="caption">无饮料</span>';}
function renderInitialMemories(){if(!detail)return;const d=detail;$('memory-effects-note').textContent=d.memory_effects_note||memoryNames[d.memory_mode||'legacy'];$('initial-memories').innerHTML=d.initial_memories?.length?d.initial_memories.map(m=>`<div class="memory-tile"><strong>${esc(m.name||m.id)}</strong><span>${esc(m.description||'')}</span></div>`).join(''):`<span class="caption">0 个 HIF 回忆效果${d.memory_mode==='none'?' · 环境禁用，不存在再动、清除眠气等 HIF 回忆触发':d.memory_mode==='hif'?' · 本局策略未选':''}</span>`;$('episode-meta').textContent=`${d.deck_size} 张计数牌 / ${d.physical_deck_size??d.initial_cards?.length} 张实际牌${supportText(d)} · 饮料容量 ${d.drink_capacity} · ${d.memory_status||memoryNames[d.memory_mode||'legacy']} · 回忆容量 ${num(d.memory_capacity)} / 已选 ${num(d.selected_memory_count)} · seed ${d.seed}`;}
function stop(){if(playTimer)clearInterval(playTimer);playTimer=null;$('play').textContent='播放';}
function renderFrame(){renderInitialMemories();const f=detail?.frames?.[cursor];if(!f)return;$('frame-board').hidden=false;$('seek').max=detail.frames.length-1;$('seek').value=cursor;$('step-label').textContent=`${cursor} / ${detail.frames.length-1}`;$('previous').disabled=cursor===0;$('next').disabled=cursor===detail.frames.length-1;$('action-banner').textContent=`第 ${f.turn} 回合 · ${f.action} · 得分变化 ${f.score_delta>=0?'+':''}${num(f.score_delta)}`;
 $('board-stats').innerHTML=[['当前得分',num(f.score)],['体力',`${num(f.stamina)} / ${num(f.max_stamina)}`],['元气',num(f.genki)],['集中',num(f.concentration)]].map(([l,v])=>`<div>${l}<strong>${v}</strong></div>`).join('');$('hand').innerHTML=cards(f.hand);$('remaining-drinks').innerHTML=drinks(f.drinks);$('buffs').innerHTML=(f.buffs||[]).map(b=>`<span class="buff-chip">${esc(b.name)} ${b.turns!=null?b.turns+' 回合':esc(JSON.stringify(b.value??b))}</span>`).join('')||'<span class="caption">暂无</span>';$('raw-state').textContent=JSON.stringify({effects:f.effects,state:f.raw_state},null,2);document.querySelectorAll('.turn-cell').forEach((e,i)=>e.classList.toggle('active',i+1===f.turn));}
async function openEpisode(row){stop();const seq=++loadSequence;selected=key(row);renderEpisodes();$('replay-empty').hidden=false;$('replay-empty').textContent='正在读取轨迹并校验回放…';$('replay-board').hidden=true;try{const d=await api(`/api/generalist/episode?mode=${encodeURIComponent(row.mode)}&file=${encodeURIComponent(row.file)}&seed=${row.seed}`);if(seq!==loadSequence)return;detail=d;cursor=0;$('episode-title').textContent=`${names[profileId(row)]||profileId(row)} · ${num(d.score??row.score)} 分`;$('verified').textContent=d.verified?'终分重放一致':'已存操作记录';$('episode-meta').textContent=`${row.deck_size} 张计数牌 / ${row.physical_deck_size??d.initial_cards?.length} 张实际牌 · 饮料容量 ${row.drink_capacity} · seed ${row.seed}`;$('initial-drinks').innerHTML=drinks(d.initial_drinks||d.drinks);$('initial-cards').innerHTML=cards(d.initial_cards||d.cards);$('deck-title').textContent=`入场卡组 · ${(d.initial_cards||d.cards||[]).length} 张实际牌`;$('turn-track').innerHTML=(d.turn_types||[]).map((t,i)=>`<span class="turn-cell turn-${esc(t)}">${i+1} ${({vocal:'红',dance:'蓝',visual:'黄'})[t]||t}</span>`).join('');$('construction-log').textContent=JSON.stringify({draft:d.draft_choices,guidance:d.guidance_choices,drinks:d.drink_choices,memory:d.memory_choices},null,2);$('frame-board').hidden=!d.frames?.length;$('action-list').innerHTML=d.frames?.length?d.frames.map((f,i)=>`<button data-step="${i}"><span>${i}. ${esc(f.action)}</span><span>${num(f.score)} 分</span></button>`).join(''):`<pre>${esc(JSON.stringify(d.submissions||d.actions||[],null,2))}</pre>`;$('replay-empty').hidden=true;$('replay-board').hidden=false;renderFrame();}catch(e){if(seq===loadSequence)$('replay-empty').textContent='轨迹读取失败：'+e.message;}}
$('refresh').onclick=()=>{refreshState();refreshLogs();refreshEpisodes();};$('chart-mode').onchange=drawChart;window.addEventListener('resize',drawChart);
$('mode-select').onchange=()=>{stop();loadSequence++;selected=null;refreshEpisodes();};$('profile-select').onchange=renderEpisodes;$('episodes-refresh').onclick=refreshEpisodes;$('episode-list').onclick=e=>{const b=e.target.closest('[data-episode]');if(b){const row=rows.find(r=>key(r)===b.dataset.episode);if(row)openEpisode(row);}};
$('memory-select').onchange=renderEpisodes;$('drink-select').onchange=renderEpisodes;
$('previous').onclick=()=>{stop();cursor=Math.max(0,cursor-1);renderFrame();};$('next').onclick=()=>{stop();cursor=Math.min(detail.frames.length-1,cursor+1);renderFrame();};$('seek').oninput=e=>{stop();cursor=Number(e.target.value);renderFrame();};$('play').onclick=()=>{if(playTimer)return stop();if(cursor>=detail.frames.length-1)cursor=0;$('play').textContent='暂停';playTimer=setInterval(()=>{if(cursor>=detail.frames.length-1)return stop();cursor++;renderFrame();},1200);};$('action-list').onclick=e=>{const b=e.target.closest('[data-step]');if(b){stop();cursor=Number(b.dataset.step);renderFrame();}};
$('log-source').onchange=()=>{logSequence++;logVersion=null;logFollow=true;$('log-output').textContent='读取中…';refreshLogs();};$('log-pause').onclick=()=>{logPaused=!logPaused;$('log-pause').textContent=logPaused?'恢复日志刷新':'暂停日志刷新';if(!logPaused)refreshLogs();};$('log-follow').onclick=()=>{logFollow=true;logVersion=null;refreshLogs();};$('log-output').addEventListener('scroll',()=>{const b=$('log-output');logFollow=b.scrollHeight-b.clientHeight-b.scrollTop<30;});
refreshState();refreshLogs();refreshEpisodes();setInterval(refreshState,5000);setInterval(refreshLogs,3000);setInterval(refreshEpisodes,20000);
